### PR TITLE
Reduce amount of warnings with pedantic compiler

### PR DESCRIPTION
**Pull request by vnepogodin**

### CODE REVIEW

**Review by COM8 — APPROVED** [review]
Thanks

**Comment by COM8** [comment]
What compiler/flags did you use for this? So we can for example add a CI run for it.

**Review by KingKili — APPROVED** [review]

**Comment by vnepogodin** [comment]
> What compiler/flags did you use for this? So we can for example add a CI run for it.

Of cause. I use these flags for clang and gcc:
`-Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wimplicit-fallthrough`

\+ gcc specific flags
`-Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wuseless-cast`

**Comment by COM8** [comment]
Thanks!

**Pull request merged**
